import Foundation

/// Parses SpecStory session markdown (v2 grammar, specstory-cli
/// pkg/session/markdown.go) into displayable exchanges.
///
/// Grammar facts honored here:
/// - Role headers: `_**User (TS)**_` / `_**Agent (MODEL TS)**_` (also
///   "Assistant"), optional " - sidechain" suffix, optional trailing
///   `<!-- message-id: ... -->` comment; `---` separators appear only on role
///   transitions and are dropped.
/// - File header lines (`<!-- Generated by SpecStory ... -->`, `# <ts>`,
///   `<!-- Provider Session id -->`) are skipped.
/// - `<think><details><summary>Thought Process</summary>BODY</details></think>`
///   becomes `.thinking`.
/// - `<tool-use data-tool-type="T" data-tool-name="N"><details><summary>S</summary>BODY</details></tool-use>`
///   becomes `.toolUse`; code fences inside the body (which may contain the
///   literal close tag) stay inside the tool segment.
/// - Code fences: ```` ```lang ```` or ```` ```lang:filename ````, closed by a
///   line of >= the same tick count; an unclosed fence is tolerated.
/// - Consecutive Agent headers with the same model dedupe (timestamp ignored).
/// - An exchange = one user turn (possibly several consecutive User headers)
///   plus the following agent output; sidechain User headers inside agent
///   output stay in the agent flow.
/// - A message body of exactly `[Object object]` renders as
///   "_Uncaptured response._".
public struct SessionTranscript: Equatable, Sendable {
    public let exchanges: [Exchange]

    public init(exchanges: [Exchange]) {
        self.exchanges = exchanges
    }

    public struct Exchange: Identifiable, Equatable, Sendable {
        public let id: Int                       // orderNumber, 0-based
        public let title: String                 // first 60 chars of first prompt line, markdown-stripped
        public let userSegments: [Segment]       // the user turn(s)
        public let agentSegments: [Segment]      // agent output until next user turn
        public let timestamp: String?            // from the user role header
        /// Raw markdown of the user turn(s), headers stripped (for copy actions).
        public let rawUserMarkdown: String
        /// Raw markdown of the agent output, role headers included (for copy actions).
        public let rawAgentMarkdown: String

        public init(
            id: Int,
            title: String,
            userSegments: [Segment],
            agentSegments: [Segment],
            timestamp: String?,
            rawUserMarkdown: String = "",
            rawAgentMarkdown: String = ""
        ) {
            self.id = id
            self.title = title
            self.userSegments = userSegments
            self.agentSegments = agentSegments
            self.timestamp = timestamp
            self.rawUserMarkdown = rawUserMarkdown
            self.rawAgentMarkdown = rawAgentMarkdown
        }
    }

    public enum Segment: Equatable, Sendable {
        case prose(String)                                     // markdown text
        case code(language: String?, filename: String?, content: String)
        case thinking(String)                                  // <think><details> body
        case toolUse(type: String, name: String, summary: String, body: String)
        case roleHeader(role: String, model: String?, timestamp: String?, sidechain: Bool)
    }

    /// Filter buckets the viewer offers for tool calls (cloud parity):
    /// File edits vs File writes split the "write" tool type by name, bash
    /// unions the bash and shell types, everything else is "other".
    public enum ToolCategory: String, CaseIterable, Sendable {
        case fileEdit
        case fileWrite
        case bash
        case other
    }

    /// Per-element totals the viewer's filter row displays.
    public struct ElementCounts: Equatable, Sendable {
        public var prompts = 0
        public var responses = 0
        public var thinking = 0
        public var fileEdits = 0
        public var fileWrites = 0
        public var bash = 0
        public var otherTools = 0

        public init() {}
    }

    public static func parse(markdown: String) -> SessionTranscript {
        var parser = Parser(lines: markdown.components(separatedBy: "\n"))
        return parser.run()
    }

    // MARK: - Tool classification

    /// Matches tool names that edit existing files rather than write new ones.
    private static let editToolNameRegex = try! NSRegularExpression(
        pattern: "edit|apply[\\s_-]?patch|search[\\s_-]?replace|str[\\s_-]?replace",
        options: [.caseInsensitive]
    )

    public static func toolCategory(type: String, name: String) -> ToolCategory {
        let lowered = type.lowercased()
        if lowered == "bash" || lowered == "shell" { return .bash }
        guard lowered == "write" else { return .other }
        let range = NSRange(name.startIndex..., in: name)
        if editToolNameRegex.firstMatch(in: name, options: [], range: range) != nil {
            return .fileEdit
        }
        return .fileWrite
    }

    public var elementCounts: ElementCounts {
        var counts = ElementCounts()
        for exchange in exchanges {
            if exchange.userSegments.contains(where: Self.isContentSegment) {
                counts.prompts += 1
            }
            var hasResponseContent = false
            for segment in exchange.agentSegments {
                switch segment {
                case .prose, .code:
                    hasResponseContent = true
                case .thinking:
                    counts.thinking += 1
                case .toolUse(let type, let name, _, _):
                    switch Self.toolCategory(type: type, name: name) {
                    case .fileEdit: counts.fileEdits += 1
                    case .fileWrite: counts.fileWrites += 1
                    case .bash: counts.bash += 1
                    case .other: counts.otherTools += 1
                    }
                case .roleHeader:
                    break
                }
            }
            if hasResponseContent { counts.responses += 1 }
        }
        return counts
    }

    private static func isContentSegment(_ segment: Segment) -> Bool {
        switch segment {
        case .prose, .code: return true
        default: return false
        }
    }

    // MARK: - Titles

    /// Plain-text title for an exchange: the first non-empty prompt line,
    /// markdown-stripped, capped at `limit` characters.
    public static func plainTitle(from segments: [Segment], limit: Int = 60) -> String {
        for segment in segments {
            guard case .prose(let text) = segment else { continue }
            for line in text.components(separatedBy: "\n") {
                let stripped = plainText(line)
                guard !stripped.isEmpty else { continue }
                if stripped.count <= limit { return stripped }
                return String(stripped.prefix(limit)).trimmingCharacters(in: .whitespaces)
            }
        }
        return "Untitled exchange"
    }

    private static let orderedListRegex = try! NSRegularExpression(pattern: "^\\d+[.)]\\s+")
    private static let linkRegex = try! NSRegularExpression(pattern: "!?\\[([^\\]]*)\\]\\([^)]*\\)")

    /// Strips one markdown line down to plain text (headers, list markers,
    /// emphasis, code spans, links).
    static func plainText(_ line: String) -> String {
        var text = line.trimmingCharacters(in: .whitespaces)
        while let first = text.first, "#>*-+`".contains(first) {
            text.removeFirst()
            text = text.trimmingCharacters(in: .whitespaces)
        }
        var range = NSRange(text.startIndex..., in: text)
        text = orderedListRegex.stringByReplacingMatches(in: text, options: [], range: range, withTemplate: "")
        range = NSRange(text.startIndex..., in: text)
        text = linkRegex.stringByReplacingMatches(in: text, options: [], range: range, withTemplate: "$1")
        text = text
            .replacingOccurrences(of: "**", with: "")
            .replacingOccurrences(of: "__", with: "")
            .replacingOccurrences(of: "`", with: "")
        let collapsed = text.split(whereSeparator: { $0 == " " || $0 == "\t" }).joined(separator: " ")
        return collapsed.trimmingCharacters(in: CharacterSet(charactersIn: "*_ "))
    }

    // MARK: - Fence helpers

    struct FenceOpen {
        let ticks: Int
        let language: String?
        let filename: String?
    }

    /// A fence opens at line start: 3+ backticks, optional `lang`, optional
    /// `:filename` suffix (mirrors the cloud viewer's fence regex).
    static func fenceOpen(_ line: String) -> FenceOpen? {
        guard line.hasPrefix("```") else { return nil }
        var ticks = 0
        var index = line.startIndex
        while index < line.endIndex, line[index] == "`" {
            ticks += 1
            index = line.index(after: index)
        }
        let rest = String(line[index...]).trimmingCharacters(in: .whitespaces)
        if rest.isEmpty { return FenceOpen(ticks: ticks, language: nil, filename: nil) }
        if let colon = rest.firstIndex(of: ":") {
            let lang = String(rest[..<colon])
            guard lang.isEmpty || isLanguageToken(lang) else { return nil }
            let file = String(rest[rest.index(after: colon)...]).trimmingCharacters(in: .whitespaces)
            return FenceOpen(ticks: ticks, language: lang.isEmpty ? nil : lang, filename: file.isEmpty ? nil : file)
        }
        guard isLanguageToken(rest) else { return nil }
        return FenceOpen(ticks: ticks, language: rest, filename: nil)
    }

    /// A closing fence is a line of only backticks with >= the opening count.
    static func fenceClose(_ line: String, ticks: Int) -> Bool {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        guard trimmed.count >= ticks else { return false }
        return trimmed.allSatisfy { $0 == "`" }
    }

    private static func isLanguageToken(_ text: String) -> Bool {
        !text.isEmpty && text.allSatisfy {
            $0.isLetter || $0.isNumber || $0 == "_" || $0 == "-" || $0 == "+" || $0 == "#" || $0 == "."
        }
    }

    /// Splits free markdown (e.g. a tool body) into prose and code segments
    /// using the same fence rules as the main parser. The viewer uses this to
    /// render tool bodies without re-tokenizing.
    public static func fenceSegments(in markdown: String) -> [Segment] {
        let lines = markdown.components(separatedBy: "\n")
        var segments = [Segment]()
        var prose = [String]()

        func flushProse() {
            let text = prose.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
            prose = []
            if !text.isEmpty { segments.append(.prose(text)) }
        }

        var index = 0
        while index < lines.count {
            if let fence = fenceOpen(lines[index]) {
                var closeAt: Int?
                var probe = index + 1
                while probe < lines.count {
                    if fenceClose(lines[probe], ticks: fence.ticks) {
                        closeAt = probe
                        break
                    }
                    probe += 1
                }
                flushProse()
                let end = closeAt ?? lines.count
                let content = trimBlankEdges(Array(lines[(index + 1)..<end]))
                segments.append(.code(language: fence.language, filename: fence.filename, content: content))
                index = (closeAt ?? lines.count - 1) + 1
            } else {
                prose.append(lines[index])
                index += 1
            }
        }
        flushProse()
        return segments
    }

    static func trimBlankEdges(_ lines: [String]) -> String {
        var trimmed = lines
        while let first = trimmed.first, first.trimmingCharacters(in: .whitespaces).isEmpty {
            trimmed.removeFirst()
        }
        while let last = trimmed.last, last.trimmingCharacters(in: .whitespaces).isEmpty {
            trimmed.removeLast()
        }
        return trimmed.joined(separator: "\n")
    }

    // MARK: - Role headers

    struct RoleHeaderMatch {
        let role: String
        let model: String?
        let timestamp: String?
        let sidechain: Bool
    }

    private static let roleHeaderRegex = try! NSRegularExpression(
        pattern: "^_\\*\\*(User|Agent|Assistant)( - sidechain)?(?:\\s*\\(([^)]*)\\))?\\*\\*_\\s*(?:<!--.*?-->)?\\s*$"
    )

    private static let timestampRegex = try! NSRegularExpression(
        pattern: "(\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:Z|[+-]\\d{2}:?\\d{2})?)\\s*$"
    )

    static func roleHeader(_ line: String) -> RoleHeaderMatch? {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        guard trimmed.hasPrefix("_**") else { return nil }
        let range = NSRange(trimmed.startIndex..., in: trimmed)
        guard let match = roleHeaderRegex.firstMatch(in: trimmed, options: [], range: range) else { return nil }

        func capture(_ index: Int) -> String? {
            guard let captureRange = Range(match.range(at: index), in: trimmed) else { return nil }
            return String(trimmed[captureRange])
        }

        let role = capture(1) ?? "User"
        let sidechain = capture(2) != nil
        var model: String?
        var timestamp: String?
        if let paren = capture(3), !paren.isEmpty {
            (model, timestamp) = splitModelTimestamp(paren)
        }
        return RoleHeaderMatch(role: role, model: model, timestamp: timestamp, sidechain: sidechain)
    }

    /// The parenthesized header payload is "MODEL TS", "MODEL", or "TS";
    /// timestamps anchor at the end so model names with spaces stay intact.
    static func splitModelTimestamp(_ paren: String) -> (String?, String?) {
        let text = paren.trimmingCharacters(in: .whitespaces)
        guard !text.isEmpty else { return (nil, nil) }
        let range = NSRange(text.startIndex..., in: text)
        guard let match = timestampRegex.firstMatch(in: text, options: [], range: range),
              let tsRange = Range(match.range(at: 1), in: text) else {
            return (text, nil)
        }
        let timestamp = String(text[tsRange])
        let model = String(text[..<tsRange.lowerBound]).trimmingCharacters(in: .whitespaces)
        return (model.isEmpty ? nil : model, timestamp)
    }

    // MARK: - Parser

    private struct Parser {
        let lines: [String]
        var index = 0
        var exchanges = [Exchange]()

        // Current exchange accumulation.
        var open = false
        var userSegments = [Segment]()
        var agentSegments = [Segment]()
        var rawUser = [String]()
        var rawAgent = [String]()
        var timestamp: String?
        var sawAgent = false
        var lastAgentIdentity: String?
        var target = Target.user
        var seenAnyContent = false
        var prose = [String]()

        enum Target { case user, agent }

        mutating func run() -> SessionTranscript {
            while index < lines.count {
                let line = lines[index]

                if let header = SessionTranscript.roleHeader(line) {
                    flushProse()
                    handle(header, rawLine: line.trimmingCharacters(in: .whitespaces))
                    index += 1
                    continue
                }

                let trimmed = line.trimmingCharacters(in: .whitespaces)

                // File-header region: skip the generator comment, the
                // "# <timestamp>" title, the provider session comment, and
                // stray separators before the first real content.
                if !seenAnyContent {
                    if trimmed.isEmpty
                        || (trimmed.hasPrefix("<!--") && trimmed.hasSuffix("-->"))
                        || trimmed.hasPrefix("# ")
                        || trimmed == "---" {
                        index += 1
                        continue
                    }
                }

                if trimmed.isEmpty, !open {
                    index += 1
                    continue
                }

                // A `---` alone is a role-transition separator only when the
                // next content line is a role header (or the file ends);
                // otherwise it is prose (a thematic break the user typed).
                if trimmed == "---", separatorBeforeRoleChange() {
                    flushProse()
                    index += 1
                    continue
                }

                ensureOpen(forStrayContent: true)
                seenAnyContent = true

                if trimmed.hasPrefix("<think>") {
                    flushProse()
                    parseThink()
                    continue
                }

                if trimmed.hasPrefix("<tool-use") {
                    flushProse()
                    parseToolUse()
                    continue
                }

                if let fence = SessionTranscript.fenceOpen(line) {
                    flushProse()
                    parseCode(fence)
                    continue
                }

                prose.append(line)
                appendRaw(line)
                index += 1
            }
            flushProse()
            finalize()
            return SessionTranscript(exchanges: exchanges)
        }

        // MARK: State transitions

        mutating func handle(_ header: RoleHeaderMatch, rawLine: String) {
            seenAnyContent = true
            let isUserRole = header.role == "User"

            if isUserRole, !header.sidechain {
                // A user turn after agent output starts the next exchange;
                // consecutive user turns share one exchange.
                if open, sawAgent { finalize() }
                ensureOpen()
                target = .user
                userSegments.append(.roleHeader(role: header.role, model: nil, timestamp: header.timestamp, sidechain: false))
                if timestamp == nil { timestamp = header.timestamp }
                return
            }

            if isUserRole {
                // Sidechain user turns are subagent prompts: they belong to
                // the agent's work, not a new exchange.
                if open, sawAgent {
                    target = .agent
                    rawAgent.append(rawLine)
                    rawAgent.append("")
                    agentSegments.append(.roleHeader(role: header.role, model: nil, timestamp: header.timestamp, sidechain: true))
                } else {
                    ensureOpen()
                    target = .user
                    userSegments.append(.roleHeader(role: header.role, model: nil, timestamp: header.timestamp, sidechain: true))
                    if timestamp == nil { timestamp = header.timestamp }
                }
                return
            }

            // Agent / Assistant.
            ensureOpen()
            sawAgent = true
            target = .agent
            rawAgent.append(rawLine)
            rawAgent.append("")
            // Consecutive same-identity agent headers dedupe (timestamp
            // ignored); the first header per exchange always renders.
            let identity = "\(header.role)|\(header.model ?? "")|\(header.sidechain)"
            if identity != lastAgentIdentity {
                lastAgentIdentity = identity
                agentSegments.append(.roleHeader(
                    role: header.role, model: header.model, timestamp: header.timestamp, sidechain: header.sidechain
                ))
            }
        }

        mutating func ensureOpen(forStrayContent: Bool = false) {
            guard !open else { return }
            open = true
            userSegments = []
            agentSegments = []
            rawUser = []
            rawAgent = []
            timestamp = nil
            sawAgent = false
            lastAgentIdentity = nil
            target = .user
            if forStrayContent {
                // Content with no role header at all reads as body text, and a
                // later User header should still start a fresh exchange.
                target = .agent
                sawAgent = true
            }
        }

        mutating func finalize() {
            flushProse()
            guard open else { return }
            open = false
            guard !userSegments.isEmpty || !agentSegments.isEmpty else { return }
            exchanges.append(Exchange(
                id: exchanges.count,
                title: SessionTranscript.plainTitle(from: userSegments),
                userSegments: userSegments,
                agentSegments: agentSegments,
                timestamp: timestamp,
                rawUserMarkdown: SessionTranscript.trimBlankEdges(rawUser),
                rawAgentMarkdown: SessionTranscript.trimBlankEdges(rawAgent)
            ))
        }

        // MARK: Content helpers

        mutating func appendRaw(_ line: String) {
            switch target {
            case .user: rawUser.append(line)
            case .agent: rawAgent.append(line)
            }
        }

        mutating func appendSegment(_ segment: Segment) {
            switch target {
            case .user: userSegments.append(segment)
            case .agent: agentSegments.append(segment)
            }
        }

        mutating func consume() -> String {
            let line = lines[index]
            appendRaw(line)
            index += 1
            return line
        }

        mutating func flushProse() {
            guard !prose.isEmpty else { return }
            var text = prose.joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
            prose = []
            guard !text.isEmpty else { return }
            if text == "[Object object]" {
                // Providers occasionally record a stringified object instead
                // of content; the cloud viewer shows this placeholder.
                text = "_Uncaptured response._"
            }
            appendSegment(.prose(text))
        }

        func separatorBeforeRoleChange() -> Bool {
            var probe = index + 1
            while probe < lines.count {
                let next = lines[probe].trimmingCharacters(in: .whitespaces)
                if next.isEmpty {
                    probe += 1
                    continue
                }
                return SessionTranscript.roleHeader(next) != nil
            }
            return true
        }

        // MARK: Block parsers

        mutating func parseThink() {
            let first = consume()
            var body = [String]()

            var remainder = first
            if let summaryEnd = remainder.range(of: "</summary>") {
                remainder = String(remainder[summaryEnd.upperBound...])
            } else if let tagEnd = remainder.range(of: "<think><details>") {
                remainder = String(remainder[tagEnd.upperBound...])
            } else if let tagEnd = remainder.range(of: "<think>") {
                remainder = String(remainder[tagEnd.upperBound...])
            }
            if let close = remainder.range(of: "</details></think>") {
                // Whole block on one line.
                let inline = String(remainder[..<close.lowerBound]).trimmingCharacters(in: .whitespacesAndNewlines)
                appendSegment(.thinking(inline))
                return
            }
            if !remainder.trimmingCharacters(in: .whitespaces).isEmpty {
                body.append(remainder)
            }

            body.append(contentsOf: scanBlockBody(closeTag: "</details></think>"))
            appendSegment(.thinking(SessionTranscript.trimBlankEdges(body)))
        }

        mutating func parseToolUse() {
            let openLine = consume()
            let rawType = attribute("data-tool-type", in: openLine) ?? ""
            let type = rawType.isEmpty ? "generic" : rawType
            let name = attribute("data-tool-name", in: openLine) ?? ""

            var summary = ""
            var body = [String]()
            var closed = false

            // The generated format puts <summary>...</summary> on the line
            // after the open tag (or occasionally on the open tag line).
            var summarySource = openLine
            var summaryFound = summarySource.contains("<summary>")
            if !summaryFound {
                while index < lines.count, lines[index].trimmingCharacters(in: .whitespaces).isEmpty {
                    _ = consume()
                }
                if index < lines.count, lines[index].contains("<summary>") {
                    summarySource = consume()
                    summaryFound = true
                }
            }
            if summaryFound, let summaryStart = summarySource.range(of: "<summary>") {
                let afterOpen = String(summarySource[summaryStart.upperBound...])
                if let summaryEnd = afterOpen.range(of: "</summary>") {
                    summary = String(afterOpen[..<summaryEnd.lowerBound])
                    let rest = String(afterOpen[summaryEnd.upperBound...])
                    if let tagClose = rest.range(of: "</details></tool-use>") {
                        let prefix = String(rest[..<tagClose.lowerBound]).trimmingCharacters(in: .whitespaces)
                        if !prefix.isEmpty { body.append(prefix) }
                        closed = true
                    } else if !rest.trimmingCharacters(in: .whitespaces).isEmpty {
                        body.append(rest)
                    }
                } else {
                    summary = afterOpen
                }
            }

            if !closed {
                body.append(contentsOf: scanBlockBody(closeTag: "</details></tool-use>"))
            }

            let cleanedSummary = summary
                .replacingOccurrences(of: "**", with: "")
                .trimmingCharacters(in: .whitespaces)
            appendSegment(.toolUse(
                type: type,
                name: name,
                summary: cleanedSummary,
                body: SessionTranscript.trimBlankEdges(body)
            ))
        }

        /// Collects lines until `closeTag` appears outside a code fence.
        /// Fences inside the block may contain the literal close tag (e.g. a
        /// Read of a session file) and must not end it. An unclosed block ends
        /// at the next role header or the end of the file.
        mutating func scanBlockBody(closeTag: String) -> [String] {
            var body = [String]()
            var fenceTicks = 0
            while index < lines.count {
                let peek = lines[index]
                if fenceTicks > 0 {
                    if SessionTranscript.fenceClose(peek, ticks: fenceTicks) { fenceTicks = 0 }
                    body.append(consume())
                    continue
                }
                if let close = peek.range(of: closeTag) {
                    let prefix = String(peek[..<close.lowerBound])
                    if !prefix.trimmingCharacters(in: .whitespaces).isEmpty { body.append(prefix) }
                    _ = consume()
                    break
                }
                if SessionTranscript.roleHeader(peek) != nil { break }
                if let fence = SessionTranscript.fenceOpen(peek) { fenceTicks = fence.ticks }
                body.append(consume())
            }
            return body
        }

        mutating func parseCode(_ fence: FenceOpen) {
            _ = consume()
            // Look ahead for the closing fence: if one exists the block is
            // consumed verbatim through it (role headers inside are fenced
            // content); an unclosed fence tolerantly ends at the next role
            // header or the end of the file.
            var hasClose = false
            var probe = index
            while probe < lines.count {
                if SessionTranscript.fenceClose(lines[probe], ticks: fence.ticks) {
                    hasClose = true
                    break
                }
                probe += 1
            }

            var content = [String]()
            while index < lines.count {
                let peek = lines[index]
                if hasClose {
                    if SessionTranscript.fenceClose(peek, ticks: fence.ticks) {
                        _ = consume()
                        break
                    }
                } else if SessionTranscript.roleHeader(peek) != nil {
                    break
                }
                content.append(consume())
            }
            appendSegment(.code(
                language: fence.language,
                filename: fence.filename,
                content: SessionTranscript.trimBlankEdges(content)
            ))
        }

        func attribute(_ name: String, in line: String) -> String? {
            guard let attrStart = line.range(of: "\(name)=\"") else { return nil }
            let afterStart = line[attrStart.upperBound...]
            guard let attrEnd = afterStart.firstIndex(of: "\"") else { return nil }
            return String(afterStart[..<attrEnd])
        }
    }
}

extension SessionTranscript {
    /// Locates the exchange a search snippet came from by matching its plain
    /// text (whitespace-collapsed) against each exchange's raw markdown.
    /// Prefers the exchange containing the longest highlighted span together
    /// with snippet context; falls back to the first exchange containing any
    /// highlighted term. Nil when nothing matches (snippet from FTS body
    /// text that markdown rendering rewrote).
    public func locateExchange(matching snippet: HighlightedSnippet) -> Int? {
        func collapse(_ text: String) -> String {
            text.components(separatedBy: .whitespacesAndNewlines).filter { !$0.isEmpty }.joined(separator: " ").lowercased()
        }
        let spans = snippet.spans
        let highlighted = spans.filter(\.isHighlighted).map { collapse($0.text) }.filter { $0.count >= 2 }
        // The longest contiguous plain run is the most discriminating anchor.
        let anchor = spans.map { collapse($0.text) }
            .filter { $0.count >= 12 }
            .max(by: { $0.count < $1.count })

        var textByExchange = [Int: String]()
        for exchange in exchanges {
            textByExchange[exchange.id] = collapse(exchange.rawUserMarkdown + " " + exchange.rawAgentMarkdown)
        }
        if let anchor {
            if let hit = exchanges.first(where: { textByExchange[$0.id]?.contains(anchor) == true }) {
                return hit.id
            }
        }
        guard !highlighted.isEmpty else { return nil }
        // Best exchange = most highlighted terms present.
        var best: (id: Int, score: Int)?
        for exchange in exchanges {
            guard let text = textByExchange[exchange.id] else { continue }
            let score = highlighted.filter { text.contains($0) }.count
            if score > 0, score > (best?.score ?? 0) {
                best = (exchange.id, score)
            }
        }
        return best?.id
    }
}
