import XCTest
@testable import SpecStoryKit

final class SessionTranscriptTests: XCTestCase {
    // MARK: - Fixture (real-shaped, three exchanges, all segment kinds)

    private let fixture = """
    <!-- Generated by SpecStory, Markdown v2.1.0 -->

    # 2026-06-30 15:24:48Z

    <!-- Claude Code Session 5459170d-2cb3-40fb-9478-5b1fd30eaefc (2026-06-30 15:24:48Z) -->

    _**User (2026-06-30 15:24:48Z)**_

    # Fix the **parser** in `markdown.go` so fences nest properly and everything else keeps working

    ---

    _**Agent (claude-opus-4-8 2026-06-30 15:24:54Z)**_

    <think><details><summary>Thought Process</summary>
    The user wants fence nesting fixed.

    I should look at the tokenizer first.
    </details></think>

    I will look at the tokenizer.

    _**Agent (claude-opus-4-8 2026-06-30 15:24:59Z)**_

    <tool-use data-tool-type="read" data-tool-name="Read"><details>
    <summary>Read markdown.go · 40 lines</summary>

    ```go:pkg/session/markdown.go
    func parse() {
        // ...
    }
    ```
    </details></tool-use>

    Here is the fix:

    ```swift:Sources/Parser.swift
    let ticks = 3
    ```

    ---

    _**User (2026-06-30 15:31:02Z)**_

    [Object object]

    ---

    _**Agent (claude-opus-4-8 2026-06-30 15:31:08Z)**_

    <tool-use data-tool-type="write" data-tool-name="Write"><details>
    <summary>Tool use: **Write**</summary>

    ````md
    # Nested doc

    ```go
    func inner() {}
    ```

    _**User (2026-01-01 00:00:00Z)**_

    </details></tool-use> baited close inside fence
    ````

    ```text
    File created successfully
    ```
    </details></tool-use>

    <tool-use data-tool-type="write" data-tool-name="apply_patch"><details>
    <summary>Tool use: **apply_patch**</summary>

    ```diff
    - old line
    + new line
    ```
    </details></tool-use>

    <tool-use data-tool-type="shell" data-tool-name="Bash"><details>
    <summary>Run the tests</summary>

    ```bash
    swift test
    ```
    </details></tool-use>

    Done.

    ---

    _**User (2026-06-30 15:40:00Z)**_

    Now try a subagent, please.

    ---

    _**Agent (claude-opus-4-8 2026-06-30 15:40:04Z)**_

    Kicking off a subagent.

    _**Agent - sidechain (2026-06-30 15:40:05Z)**_

    Analyze the schema.

    _**Agent - sidechain (claude-haiku-4-5 2026-06-30 15:40:07Z)**_

    _**Agent - sidechain (claude-haiku-4-5 2026-06-30 15:40:08Z)**_

    On it.

    _**Agent (claude-opus-4-8 2026-06-30 15:40:20Z)**_

    Wrapping up with an unclosed fence:

    ```python
    print("still going
    """

    // MARK: - Whole-fixture shape

    func testFixtureParsesThreeExchanges() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        XCTAssertEqual(transcript.exchanges.count, 3)
        XCTAssertEqual(transcript.exchanges.map(\.id), [0, 1, 2])
    }

    func testFileHeaderLinesAreSkipped() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        for exchange in transcript.exchanges {
            for segment in exchange.userSegments + exchange.agentSegments {
                if case .prose(let text) = segment {
                    XCTAssertFalse(text.contains("Generated by SpecStory"))
                    XCTAssertFalse(text.contains("Claude Code Session"))
                    XCTAssertFalse(text.contains("# 2026-06-30 15:24:48Z"))
                }
            }
        }
        // The first user prose is the actual prompt.
        guard case .prose(let prompt)? = firstProse(transcript.exchanges[0].userSegments) else {
            return XCTFail("expected a user prose segment")
        }
        XCTAssertTrue(prompt.contains("Fix the **parser**"))
    }

    func testExchangeTimestampAndTitle() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        let first = transcript.exchanges[0]
        XCTAssertEqual(first.timestamp, "2026-06-30 15:24:48Z")
        XCTAssertTrue(first.title.hasPrefix("Fix the parser in markdown.go"), "got: \(first.title)")
        XCTAssertLessThanOrEqual(first.title.count, 60)
        // Markdown syntax stripped from the title.
        XCTAssertFalse(first.title.contains("#"))
        XCTAssertFalse(first.title.contains("*"))
        XCTAssertFalse(first.title.contains("`"))
    }

    func testAllSegmentKindsPresent() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        let agentSegments = transcript.exchanges.flatMap(\.agentSegments)

        XCTAssertTrue(agentSegments.contains { if case .thinking = $0 { return true }; return false })
        XCTAssertTrue(agentSegments.contains { if case .prose = $0 { return true }; return false })
        XCTAssertTrue(agentSegments.contains { if case .code = $0 { return true }; return false })
        XCTAssertTrue(agentSegments.contains { if case .toolUse = $0 { return true }; return false })
        XCTAssertTrue(agentSegments.contains { if case .roleHeader = $0 { return true }; return false })
    }

    // MARK: - Exchange 1: thinking, tool, fences, dedup

    func testThinkingBlockBody() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        let thinking = transcript.exchanges[0].agentSegments.compactMap { segment -> String? in
            if case .thinking(let text) = segment { return text }
            return nil
        }
        XCTAssertEqual(thinking.count, 1)
        XCTAssertTrue(thinking[0].contains("The user wants fence nesting fixed."))
        XCTAssertTrue(thinking[0].contains("I should look at the tokenizer first."))
        XCTAssertFalse(thinking[0].contains("Thought Process"))
        XCTAssertFalse(thinking[0].contains("</details>"))
    }

    func testConsecutiveSameModelAgentHeadersDedupe() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        let headers = roleHeaders(transcript.exchanges[0].agentSegments)
        // Two claude-opus-4-8 headers in the source collapse to one.
        XCTAssertEqual(headers.count, 1)
        XCTAssertEqual(headers[0].model, "claude-opus-4-8")
        XCTAssertEqual(headers[0].timestamp, "2026-06-30 15:24:54Z")
        XCTAssertFalse(headers[0].sidechain)
    }

    func testToolUseWithProviderSummary() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        guard case .toolUse(let type, let name, let summary, let body)? = firstToolUse(transcript.exchanges[0].agentSegments) else {
            return XCTFail("expected a tool use segment")
        }
        XCTAssertEqual(type, "read")
        XCTAssertEqual(name, "Read")
        XCTAssertEqual(summary, "Read markdown.go · 40 lines")
        XCTAssertTrue(body.contains("func parse()"))
        XCTAssertTrue(body.contains("```go:pkg/session/markdown.go"))
        XCTAssertFalse(body.contains("</details></tool-use>"))
    }

    func testCodeFenceWithLanguageAndFilename() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        let codes = codeSegments(transcript.exchanges[0].agentSegments)
        XCTAssertEqual(codes.count, 1)
        XCTAssertEqual(codes[0].language, "swift")
        XCTAssertEqual(codes[0].filename, "Sources/Parser.swift")
        XCTAssertEqual(codes[0].content, "let ticks = 3")
    }

    // MARK: - Exchange 2: uncaptured prompt, nested fences, classification

    func testObjectObjectBecomesUncapturedResponse() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        guard case .prose(let text)? = firstProse(transcript.exchanges[1].userSegments) else {
            return XCTFail("expected a user prose segment")
        }
        XCTAssertEqual(text, "_Uncaptured response._")
    }

    func testNestedFencesStayInsideToolBody() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        let tools = toolUses(transcript.exchanges[1].agentSegments)
        XCTAssertEqual(tools.count, 3)

        let write = tools[0]
        XCTAssertEqual(write.type, "write")
        XCTAssertEqual(write.name, "Write")
        XCTAssertEqual(write.summary, "Tool use: Write")
        // The four-tick fence swallows the baited close tag, the role-header
        // lookalike, and the inner three-tick fence.
        XCTAssertTrue(write.body.contains("func inner() {}"))
        XCTAssertTrue(write.body.contains("</details></tool-use> baited close inside fence"))
        XCTAssertTrue(write.body.contains("_**User (2026-01-01 00:00:00Z)**_"))
        XCTAssertTrue(write.body.contains("File created successfully"))

        // The baited lines do not leak new exchanges or stray segments.
        XCTAssertEqual(transcript.exchanges.count, 3)
        XCTAssertEqual(tools[1].name, "apply_patch")
        XCTAssertEqual(tools[2].name, "Bash")

        // Prose after the tool run survives.
        let prose = proseTexts(transcript.exchanges[1].agentSegments)
        XCTAssertTrue(prose.contains { $0.contains("Done.") })
    }

    func testToolCategoryClassification() {
        let cases: [(type: String, name: String, expected: SessionTranscript.ToolCategory)] = [
            ("write", "Write", .fileWrite),
            ("write", "Edit", .fileEdit),
            ("write", "MultiEdit", .fileEdit),
            ("write", "apply_patch", .fileEdit),
            ("write", "ApplyPatch", .fileEdit),
            ("write", "str_replace_editor", .fileEdit),
            ("write", "search-replace", .fileEdit),
            ("write", "NotebookEdit", .fileEdit),
            ("bash", "Bash", .bash),
            ("shell", "Bash", .bash),
            ("Shell", "run_terminal_cmd", .bash),
            ("read", "Read", .other),
            ("search", "Glob", .other),
            ("grep", "Grep", .other),
            ("mcp", "mcp__playwright__click", .other),
            ("task", "Task", .other),
            ("generic", "WebFetch", .other),
            ("unknown", "Agent", .other),
        ]
        for testCase in cases {
            XCTAssertEqual(
                SessionTranscript.toolCategory(type: testCase.type, name: testCase.name),
                testCase.expected,
                "type=\(testCase.type) name=\(testCase.name)"
            )
        }
    }

    func testDefaultSummaryBoldMarkersStripped() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        let tools = toolUses(transcript.exchanges[1].agentSegments)
        XCTAssertEqual(tools[1].summary, "Tool use: apply_patch")
        XCTAssertEqual(tools[2].summary, "Run the tests")
    }

    // MARK: - Exchange 3: sidechain, dedup reset, unclosed fence

    func testSidechainHeadersFlaggedAndDeduped() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        let headers = roleHeaders(transcript.exchanges[2].agentSegments)
        // opus, sidechain (no model), sidechain haiku (second haiku deduped),
        // then opus again (identity changed back, so it renders).
        XCTAssertEqual(headers.count, 4)
        XCTAssertEqual(headers[0].model, "claude-opus-4-8")
        XCTAssertFalse(headers[0].sidechain)
        XCTAssertNil(headers[1].model)
        XCTAssertTrue(headers[1].sidechain)
        XCTAssertEqual(headers[1].timestamp, "2026-06-30 15:40:05Z")
        XCTAssertEqual(headers[2].model, "claude-haiku-4-5")
        XCTAssertTrue(headers[2].sidechain)
        XCTAssertEqual(headers[3].model, "claude-opus-4-8")
        XCTAssertFalse(headers[3].sidechain)
    }

    func testUnclosedFenceToleratedAsCode() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        let codes = codeSegments(transcript.exchanges[2].agentSegments)
        XCTAssertEqual(codes.count, 1)
        XCTAssertEqual(codes[0].language, "python")
        XCTAssertTrue(codes[0].content.contains("print(\"still going"))
    }

    // MARK: - Sidechain user turns do not split exchanges

    func testSidechainUserTurnStaysInAgentFlow() {
        let markdown = """
        _**User (2026-01-01 10:00:00Z)**_

        Do the thing.

        ---

        _**Agent (claude-opus-4-8 2026-01-01 10:00:05Z)**_

        Starting.

        _**User - sidechain (2026-01-01 10:00:06Z)**_

        Subagent prompt text.

        _**Agent - sidechain (claude-haiku-4-5 2026-01-01 10:00:08Z)**_

        Subagent answer.

        ---

        _**User (2026-01-01 10:05:00Z)**_

        Second real prompt.
        """
        let transcript = SessionTranscript.parse(markdown: markdown)
        XCTAssertEqual(transcript.exchanges.count, 2)

        let first = transcript.exchanges[0]
        let sidechainUser = roleHeaders(first.agentSegments).first { $0.role == "User" }
        XCTAssertNotNil(sidechainUser)
        XCTAssertTrue(sidechainUser?.sidechain ?? false)
        XCTAssertTrue(proseTexts(first.agentSegments).contains { $0.contains("Subagent prompt text.") })

        XCTAssertEqual(transcript.exchanges[1].title, "Second real prompt.")
    }

    // MARK: - Consecutive user headers, Assistant role, message ids

    func testConsecutiveUserHeadersShareOneExchange() {
        let markdown = """
        _**User (2026-01-01 10:00:00Z)**_

        First part.

        _**User (2026-01-01 10:00:02Z)**_

        Second part.

        ---

        _**Agent**_

        Reply.
        """
        let transcript = SessionTranscript.parse(markdown: markdown)
        XCTAssertEqual(transcript.exchanges.count, 1)
        let exchange = transcript.exchanges[0]
        XCTAssertEqual(roleHeaders(exchange.userSegments).count, 2)
        XCTAssertEqual(proseTexts(exchange.userSegments), ["First part.", "Second part."])
        XCTAssertEqual(exchange.timestamp, "2026-01-01 10:00:00Z")
        XCTAssertEqual(proseTexts(exchange.agentSegments), ["Reply."])
    }

    func testAssistantRoleActsAsAgent() {
        let markdown = """
        _**User**_

        Hello.

        ---

        _**Assistant**_

        Hi there.

        ---

        _**User**_

        Bye.
        """
        let transcript = SessionTranscript.parse(markdown: markdown)
        XCTAssertEqual(transcript.exchanges.count, 2)
        let headers = roleHeaders(transcript.exchanges[0].agentSegments)
        XCTAssertEqual(headers.count, 1)
        XCTAssertEqual(headers[0].role, "Assistant")
        XCTAssertNil(headers[0].model)
    }

    func testMessageIDCommentOnHeaderLine() {
        let markdown = """
        _**User (2026-01-01 10:00:00Z)**_<!-- message-id: abc-123 -->

        Prompt with id.

        ---

        _**Agent (m1 2026-01-01 10:00:04Z)**_<!-- message-id: def-456 -->

        Reply.
        """
        let transcript = SessionTranscript.parse(markdown: markdown)
        XCTAssertEqual(transcript.exchanges.count, 1)
        XCTAssertEqual(transcript.exchanges[0].timestamp, "2026-01-01 10:00:00Z")
        let headers = roleHeaders(transcript.exchanges[0].agentSegments)
        XCTAssertEqual(headers.first?.model, "m1")
    }

    // MARK: - Separators vs prose

    func testThematicBreakInsideProseIsKept() {
        let markdown = """
        _**User (2026-01-01 10:00:00Z)**_

        Front matter below

        ---

        not a header, just text

        ---

        _**Agent**_

        ok
        """
        let transcript = SessionTranscript.parse(markdown: markdown)
        XCTAssertEqual(transcript.exchanges.count, 1)
        guard case .prose(let text)? = firstProse(transcript.exchanges[0].userSegments) else {
            return XCTFail("expected user prose")
        }
        // The first --- is content (next line is not a role header); the
        // second is a role-transition separator and is dropped.
        XCTAssertTrue(text.contains("---"))
        XCTAssertTrue(text.contains("not a header, just text"))
        XCTAssertEqual(proseTexts(transcript.exchanges[0].agentSegments), ["ok"])
    }

    // MARK: - Fence nesting at the prose level

    func testFourTickFenceSwallowsThreeTickFence() {
        let markdown = """
        _**User**_

        Prompt.

        ---

        _**Agent**_

        ````md
        ```go
        inner
        ```
        ````

        after
        """
        let transcript = SessionTranscript.parse(markdown: markdown)
        let codes = codeSegments(transcript.exchanges[0].agentSegments)
        XCTAssertEqual(codes.count, 1)
        XCTAssertEqual(codes[0].language, "md")
        XCTAssertEqual(codes[0].content, "```go\ninner\n```")
        XCTAssertTrue(proseTexts(transcript.exchanges[0].agentSegments).contains("after"))
    }

    func testClosingFenceMayHaveMoreTicks() {
        let markdown = """
        _**User**_

        Prompt.

        ---

        _**Agent**_

        ```go
        content
        ````
        """
        let transcript = SessionTranscript.parse(markdown: markdown)
        let codes = codeSegments(transcript.exchanges[0].agentSegments)
        XCTAssertEqual(codes.count, 1)
        XCTAssertEqual(codes[0].content, "content")
    }

    // MARK: - Empty and degenerate input

    func testEmptyMarkdown() {
        XCTAssertEqual(SessionTranscript.parse(markdown: "").exchanges.count, 0)
        XCTAssertEqual(SessionTranscript.parse(markdown: "\n\n  \n").exchanges.count, 0)
    }

    func testHeaderOnlyFileYieldsNoExchanges() {
        let markdown = """
        <!-- Generated by SpecStory, Markdown v2.1.0 -->

        # 2026-06-30 15:24:48Z

        <!-- Claude Code Session abc (2026-06-30 15:24:48Z) -->
        """
        XCTAssertEqual(SessionTranscript.parse(markdown: markdown).exchanges.count, 0)
    }

    // MARK: - Titles

    func testTitleCapsAtSixtyCharacters() {
        let longLine = String(repeating: "word ", count: 40)
        let markdown = """
        _**User (2026-01-01 10:00:00Z)**_

        > \(longLine)

        ---

        _**Agent**_

        ok
        """
        let transcript = SessionTranscript.parse(markdown: markdown)
        let title = transcript.exchanges[0].title
        XCTAssertLessThanOrEqual(title.count, 60)
        XCTAssertTrue(title.hasPrefix("word word"))
    }

    func testTitleFallsBackWhenPromptEmpty() {
        let markdown = """
        _**Agent (m1 2026-01-01 10:00:00Z)**_

        Agent-only content.
        """
        let transcript = SessionTranscript.parse(markdown: markdown)
        XCTAssertEqual(transcript.exchanges.count, 1)
        XCTAssertEqual(transcript.exchanges[0].title, "Untitled exchange")
    }

    // MARK: - Raw markdown capture

    func testRawMarkdownCapture() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        let first = transcript.exchanges[0]
        XCTAssertTrue(first.rawUserMarkdown.contains("Fix the **parser**"))
        XCTAssertFalse(first.rawUserMarkdown.contains("_**User"))
        XCTAssertTrue(first.rawAgentMarkdown.hasPrefix("_**Agent (claude-opus-4-8"))
        XCTAssertTrue(first.rawAgentMarkdown.contains("<tool-use data-tool-type=\"read\""))
    }

    // MARK: - Element counts

    func testElementCounts() {
        let counts = SessionTranscript.parse(markdown: fixture).elementCounts
        XCTAssertEqual(counts.prompts, 3)
        XCTAssertEqual(counts.responses, 3)
        XCTAssertEqual(counts.thinking, 1)
        XCTAssertEqual(counts.fileWrites, 1)   // Write
        XCTAssertEqual(counts.fileEdits, 1)    // apply_patch
        XCTAssertEqual(counts.bash, 1)         // shell/Bash
        XCTAssertEqual(counts.otherTools, 1)   // read/Read
    }

    // MARK: - fenceSegments helper (tool body rendering)

    func testFenceSegmentsSplitsToolBody() {
        let transcript = SessionTranscript.parse(markdown: fixture)
        let write = toolUses(transcript.exchanges[1].agentSegments)[0]
        let segments = SessionTranscript.fenceSegments(in: write.body)
        let codes = segments.compactMap { segment -> (language: String?, content: String)? in
            if case .code(let language, _, let content) = segment { return (language, content) }
            return nil
        }
        XCTAssertEqual(codes.count, 2)
        XCTAssertEqual(codes[0].language, "md")
        XCTAssertTrue(codes[0].content.contains("func inner() {}"))
        XCTAssertTrue(codes[0].content.contains("</details></tool-use> baited close inside fence"))
        XCTAssertEqual(codes[1].language, "text")
        XCTAssertEqual(codes[1].content, "File created successfully")
    }

    func testFenceSegmentsProseAndUnclosedFence() {
        let body = """
        **Input:**

        - path: `/tmp/x`

        ```
        unclosed output
        """
        let segments = SessionTranscript.fenceSegments(in: body)
        XCTAssertEqual(segments.count, 2)
        guard case .prose(let prose) = segments[0], case .code(_, _, let content) = segments[1] else {
            return XCTFail("expected prose then code, got \(segments)")
        }
        XCTAssertTrue(prose.contains("**Input:**"))
        XCTAssertEqual(content, "unclosed output")
    }

    // MARK: - Helpers

    private func firstProse(_ segments: [SessionTranscript.Segment]) -> SessionTranscript.Segment? {
        segments.first { if case .prose = $0 { return true }; return false }
    }

    private func firstToolUse(_ segments: [SessionTranscript.Segment]) -> SessionTranscript.Segment? {
        segments.first { if case .toolUse = $0 { return true }; return false }
    }

    private func proseTexts(_ segments: [SessionTranscript.Segment]) -> [String] {
        segments.compactMap { if case .prose(let text) = $0 { return text }; return nil }
    }

    private func codeSegments(_ segments: [SessionTranscript.Segment]) -> [(language: String?, filename: String?, content: String)] {
        segments.compactMap {
            if case .code(let language, let filename, let content) = $0 { return (language, filename, content) }
            return nil
        }
    }

    private func toolUses(_ segments: [SessionTranscript.Segment]) -> [(type: String, name: String, summary: String, body: String)] {
        segments.compactMap {
            if case .toolUse(let type, let name, let summary, let body) = $0 { return (type, name, summary, body) }
            return nil
        }
    }

    private func roleHeaders(_ segments: [SessionTranscript.Segment]) -> [(role: String, model: String?, timestamp: String?, sidechain: Bool)] {
        segments.compactMap {
            if case .roleHeader(let role, let model, let timestamp, let sidechain) = $0 {
                return (role, model, timestamp, sidechain)
            }
            return nil
        }
    }
}
